luffy_crm/urls.py
from django.contrib import admin
from django.urls import path, re_path,include
from stark.service.v1 import site
from web.views import account

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^stark/', site.urls),
    re_path(r'^login/', account.login, name='login'),
    re_path(r'^logout/', account.logout, name='logout'),
    re_path(r'^index/', account.index, name='index'),
    re_path(r'^rbac/',include(('rbac.urls','rbac'),namespace='rbac')),
]

rbac/service/urls.py
from django.urls import reverse
from django.http import QueryDict



def memory_url(request, name, *args, **kwargs):
    """
    生成带有原搜索条件的URL
    :param request:
    :param name:
    :return:
    """
    basic_url = reverse(name,args=args,kwargs=kwargs)
    # 当前URL无参数
    if not request.GET:
        return basic_url
    # 拿到了原搜索条件

    query_dict = QueryDict(mutable=True)
    # 相当于_filter = "mid=2"(客户端传过来后面的参数 )
    query_dict['_filter'] = request.GET.urlencode()
    return '%s?%s' % (basic_url, query_dict.urlencode())



def memory_reverse(request,name,*args,**kwargs):
    """
    反向生成URL
    在URL中 把原来的搜索条件获取
    在url中将原来搜索条件 如filter = mid=1
    :param request:
    :param name:
    :param args:
    :param kwargs:
    :return:
    """
    url = reverse(name,args=args,kwargs=kwargs)
    origin_params = request.GET.get('_filter')
    if origin_params:
        url = '%s?%s' % (url, origin_params,)
    return url

rbac/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from rbac.views import role, user, menu

urlpatterns = [
    re_path(r'^role/list/', role.role_list, name='role_list'),
    re_path(r'^role/add/', role.role_add, name='role_add'),
    re_path(r'^role/del/(?P<pk>\d+)/$', role.role_del, name='role_del'),
    re_path(r'^role/edit/(?P<pk>\d+)/$', role.role_edit, name='role_edit'),

    re_path(r'^user/list/', user.user_list, name='user_list'),
    re_path(r'^user/add/', user.user_add, name='user_add'),
    re_path(r'^user/del/(?P<pk>\d+)/$', user.user_del, name='user_del'),
    re_path(r'^user/edit/(?P<pk>\d+)/$', user.user_edit, name='user_edit'),
    re_path(r'^user/reset/password/(?P<pk>\d+)/$', user.user_reset_pwd, name='user_reset_pwd'),

    re_path(r'^menu/list/', menu.menu_list, name='menu_list'),
    re_path(r'^menu/add/', menu.menu_add, name='menu_add'),
    re_path(r'^menu/edit/(?P<pk>\d+)/$', menu.menu_edit, name='menu_edit'),
    re_path(r'^menu/del/(?P<pk>\d+)/$', menu.menu_del, name='menu_del'),

    re_path(r'^second/menu/add/(?P<menu_id>\d+)/$', menu.second_menu_add, name='second_menu_add'),
    re_path(r'^second/menu/edit/(?P<pk>\d+)/$', menu.second_menu_edit, name='second_menu_edit'),
    re_path(r'^second/menu/del/(?P<pk>\d+)/$', menu.second_menu_del, name='second_menu_del'),

    re_path(r'^thirst/menu/add/(?P<second_menu_id>\d+)/$', menu.thirst_menu_add, name='thirst_menu_add'),
    re_path(r'^thirst/menu/edit/(?P<pk>\d+)/$', menu.thirst_menu_edit, name='thirst_menu_edit'),
    re_path(r'^thirst/menu/del/(?P<pk>\d+)/$', menu.thirst_menu_del, name='thirst_menu_del'),


    re_path(r'^multi/permissions/$', menu.multi_permissions, name='multi_permissions'),
    re_path(r'^multi/permissions/del/(?P<pk>\d+)/$', menu.multi_permissions_del, name='multi_permissions_del'),
    re_path(r'^distribute/permissions/$', menu.distribute_permissions, name='distribute_permissions'),

]

rbac/forms/base.py
from django import forms


class BootStrapModelForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(BootStrapModelForm, self).__init__(*args, **kwargs)
        # 统一给ModelForm生成字段添加样式
        for name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

rbac/service/routes.py
import re
from collections import OrderedDict
from django.conf import settings
from django.utils.module_loading import import_string
from django.urls.conf import URLResolver, URLPattern

# 自动获取项目中所有的权限

def check_url_exclude(url):
    """
    排除一些特定的url
    :param url:
    :return:
    """
    for regex in settings.AUTO_DISCOVER_EXCLUDE:
        if re.match(regex, url):
            return True


def recursion_urls(pre_namespace, pre_url, urlpatterns, url_ordered_dict):
    """
   递归的去获取URL
   :param pre_namespace: namespace前缀，以后用户拼接name
   :param pre_url: url前缀，以后用于拼接url
   :param urlpatterns: 路由关系列表
   :param url_ordered_dict: 用于保存递归中获取的所有路由
   :return:
   """
    for item in urlpatterns:
        if isinstance(item,URLPattern):
            if not item.name:
                continue

            if pre_namespace:
                name = '%s:%s' % (pre_namespace, item.name)
            else:
                name = item.name
            it = str(item.pattern)
            url = pre_url + it

            url = url.replace('^', '').replace('$', '')

            if check_url_exclude(url):
                continue

            url_ordered_dict[name] = {'name': name, 'url': url}
        elif isinstance(item, URLResolver):
            if pre_namespace:
                if item.namespace:
                    namespace = "%s:%s" % (pre_namespace, item.namespace,)
                else:
                    namespace = pre_namespace
            else:
                if item.namespace:
                    namespace = item.namespace
                else:
                     namespace = None

            it = str(item.pattern)
            # 递归函数
            recursion_urls(namespace, pre_url + it, item.url_patterns, url_ordered_dict)


def get_all_url_dict():
    """
    获取项目中所有的URL(必须有那么别名)
    :return:
    """
    url_ordered_dict = OrderedDict()
    md = import_string(settings.ROOT_URLCONF)  # 根目录地址settings.ROOT_URLCONF
    recursion_urls(None, '/', md.urlpatterns, url_ordered_dict)
    return url_ordered_dict

rbac/views/menu.py
from web.models import UserInfo
from rbac import models

from django.shortcuts import render, redirect, HttpResponse
from rbac.forms.menu import MenuModelForm, SecondMenuModelForm, PermissionModelForm
from rbac.forms.menu import MultiEditPermissionForm, MultiAddPermissionForm
from django.urls import reverse
from rbac.service.urls import memory_reverse
from rbac.service.routes import get_all_url_dict
from collections import OrderedDict
from django.forms import formset_factory
from django.utils.module_loading import import_string
from django.conf import settings


def menu_list(request):
    """
    菜单的权限列表
    :param request:
    :return:
    """
    menus = models.Menu.objects.all()
    # 用户选择的一级菜单
    menu_id = request.GET.get('mid')
    # 用户选择的二级菜单
    second_menu_id = request.GET.get('sid')
    # 用户选择的三级菜单
    thirst_menu_id = request.GET.get('tid')
    menu_exists = models.Menu.objects.filter(id=menu_id).exists()
    second_menu_exists = models.Permission.objects.filter(pid_id=second_menu_id).exists()
    # if not menu_exists:
    #     menu_id = None
    if menu_id:
        second_menus = models.Permission.objects.filter(menu_id=menu_id)
    else:
        second_menus = []
    # if not second_menu_exists:
    #     second_menu_id = None
    if second_menu_id:
        thirst_menus = models.Permission.objects.filter(pid_id=second_menu_id)
    else:
        thirst_menus = []
    return render(request, 'rbac/menu_list.html',
                  {
                      "menus": menus,
                      "menu_id": menu_id,
                      'second_menus': second_menus,
                      'second_menu_id': second_menu_id,
                      'thirst_menus': thirst_menus,
                      'thirst_menu_id': thirst_menu_id,
                  })


def menu_add(request):
    if request.method == 'GET':
        form = MenuModelForm()
        return render(request, 'rbac/change.html', {'form': form})

    form = MenuModelForm(data=request.POST)
    if form.is_valid():
        form.save()

        return redirect(memory_reverse(request, 'rbac:menu_list'))
    return render(request, 'rbac/change.html', {'form': form})


def menu_edit(request, pk):
    obj = models.Menu.objects.get(id=pk)
    if not obj:
        return HttpResponse('菜单不存在')
    if request.method == 'GET':
        form = MenuModelForm(instance=obj)
        return render(request, 'rbac/change.html', {'form': form})
    form = MenuModelForm(data=request.POST, instance=obj)
    if form.is_valid():
        form.save()
        return redirect(memory_reverse(request, 'rbac:menu_list'))
    return render(request, 'rbac/change.html', {'form': form})


def menu_del(request, pk):
    # obj2 = models.Menu.objects.get(id=pk)
    # if request.method == "GET":
    #     return render(request, 'rbac/delete.html', {'obj2': obj2})
    # obj2.delete()
    # return redirect(memory_reverse(request,'rbac:menu_list'))
    url = memory_reverse(request, 'rbac:menu_list')
    if request.method == 'GET':
        return render(request, 'rbac/delete.html', {'cancel': url})

    models.Menu.objects.filter(id=pk).delete()
    return redirect(url)


def second_menu_add(request, menu_id):
    """
    添加二级菜单
    :param request:
    :return:
    """
    menu_object = models.Menu.objects.get(id=menu_id)
    if request.method == 'GET':
        form = SecondMenuModelForm(initial={'menu': menu_object})
        return render(request, 'rbac/change.html', {'form': form})

    form = SecondMenuModelForm(data=request.POST)
    if form.is_valid():
        form.save()

        return redirect(memory_reverse(request, 'rbac:menu_list'))
    return render(request, 'rbac/change.html', {'form': form})


def second_menu_edit(request, pk):
    """
    添加二级菜单
    :param request:
    :return:
    """
    permission_object = models.Permission.objects.get(id=pk)
    if request.method == 'GET':
        form = SecondMenuModelForm(instance=permission_object)
        return render(request, 'rbac/change.html', {'form': form})

    form = SecondMenuModelForm(data=request.POST, instance=permission_object)
    if form.is_valid():
        form.save()

        return redirect(memory_reverse(request, 'rbac:menu_list'))
    return render(request, 'rbac/change.html', {'form': form})


def second_menu_del(request, pk):
    url = memory_reverse(request, 'rbac:menu_list')
    if request.method == 'GET':
        return render(request, 'rbac/delete.html', {'cancel': url})

    models.Permission.objects.filter(id=pk).delete()
    return redirect(url)


def thirst_menu_add(request, second_menu_id):
    """
    添加二级菜单
    :param request:
    :return:
    """
    if request.method == 'GET':
        form = PermissionModelForm()
        return render(request, 'rbac/change.html', {'form': form})

    form = PermissionModelForm(data=request.POST)
    if form.is_valid():
        second_menu_obj = models.Permission.objects.filter(id=second_menu_id).first()
        if not second_menu_obj:
            return HttpResponse('二级菜单不存在,请重新选择')
        # form.instance中包含用户提交的所有的值
        # 相当于做了下面的事情
        # instance = models.Permission(title='',name='',url='',)
        # instance.pid = second_menu_obj
        # instance.save
        form.instance.pid = second_menu_obj
        form.save()
        return redirect(memory_reverse(request, 'rbac:menu_list'))
    return render(request, 'rbac/change.html', {'form': form})


def thirst_menu_edit(request, pk):
    """
    编辑三级菜单
    :param request:
    :return:
    """
    permission_object = models.Permission.objects.get(id=pk)
    if request.method == 'GET':
        form = PermissionModelForm(instance=permission_object)
        return render(request, 'rbac/change.html', {'form': form})

    form = PermissionModelForm(data=request.POST, instance=permission_object)
    if form.is_valid():
        form.save()

        return redirect(memory_reverse(request, 'rbac:menu_list'))
    return render(request, 'rbac/change.html', {'form': form})


def thirst_menu_del(request, pk):
    url = memory_reverse(request, 'rbac:menu_list')
    if request.method == 'GET':
        return render(request, 'rbac/delete.html', {'cancel': url})

    models.Permission.objects.filter(id=pk).delete()
    return redirect(url)


def multi_permissions(request):
    """
    批量操作权限
    :param request:
    :return:
    """
    post_type = request.GET.get('type')
    generate_formset_add_class = formset_factory(MultiAddPermissionForm, extra=0)
    update_formset_class = formset_factory(MultiEditPermissionForm, extra=0)
    generate_formset = None
    update_formset = None
    # 批量添加
    if request.method == 'POST' and post_type == 'generate':

        formset = generate_formset_add_class(data=request.POST)
        if formset.is_valid():
            object_list = []
            post_row_list = formset.cleaned_data
            has_error = False

            for i in range(0, formset.total_form_count()):
                row_dict = post_row_list[i]

                try:
                    new_object = models.Permission(**row_dict)
                    # 判断唯一索引
                    new_object.validate_unique()
                    object_list.append(new_object)
                except Exception as e:
                    # 把错误信息添加到formset里面
                    formset.errors[i].update(e)
                    generate_formset = formset
                    has_error = True

            # 要先判断是否有错误信息
            # 批量添加
            if not has_error:
                models.Permission.objects.bulk_create(object_list, batch_size=100)
        else:
            generate_formset = formset

    # 批量更新
    if request.method == 'POST' and post_type == 'update':

        formset = update_formset_class(data=request.POST)
        if formset.is_valid():
            post_row_list = formset.cleaned_data

            for i in range(0, formset.total_form_count()):
                row_dict = post_row_list[i]
                permission_id = row_dict.pop("id")
                # print(row_dict)
                try:
                    row_object = models.Permission.objects.filter(id=permission_id).first()
                    for k, v in row_dict.items():
                        setattr(row_object, k, v)
                    row_object.validate_unique()
                    row_object.save()
                except Exception as e:
                    # 把错误信息添加到formset里面
                    formset.errors[i].update(e)
                    update_formset = formset

        else:
            update_formset = formset

    # 获取项目中所有的URL
    all_url_dict = get_all_url_dict()
    # 集合 项目中所有name集合
    router_name_set = set(all_url_dict.keys())

    # 获取数据库中所有的URL
    permissions = models.Permission.objects.all().values('id', 'title', 'name', 'url', 'menu_id', 'pid_id')
    permission_dict = OrderedDict()
    # 集合
    permission_name_set = set()
    for row in permissions:
        permission_dict[row['name']] = row
        permission_name_set.add(row['name'])

    for name, value in permission_dict.items():
        router_row_dict = all_url_dict.get(name)
        if not router_row_dict:
            continue
        if value['url'] != router_row_dict['url']:
            value['url'] = '路由和数据库不一致'

    # 应该添加,删除,修改的权限有哪些?
    # 计算出应该增加的name
    if not generate_formset:
        generate_name_list = router_name_set - permission_name_set
        generate_formset = generate_formset_add_class(
            initial=[row_dict for name, row_dict in all_url_dict.items() if name in generate_name_list])
    # 计算出应该删除的name
    delete_name_list = permission_name_set - router_name_set
    delete_row_list = [row_dict1 for name, row_dict1 in permission_dict.items() if name in delete_name_list]

    # 计算出应该更新的name
    # 操作要有隐形的ID 要不然无法正确更新
    if not update_formset:
        update_name_list = router_name_set & permission_name_set
        update_formset = update_formset_class(
            initial=[row_dict for name, row_dict in permission_dict.items() if name in update_name_list])

rbac/views/role.py
# 角色管理

from rbac import models
from django.shortcuts import render, redirect, HttpResponse
from django.urls import reverse
from rbac.forms.role import RoleModelForm


def role_list(request):
    role_queryset = models.Role.objects.all()

    return render(request, 'rbac/role_list.html', {'roles': role_queryset})


def role_add(request):
    origin_url = reverse('rbac:role_list')
    if request.method == 'GET':
        form = RoleModelForm()
        return render(request, 'rbac/change.html', {'form':form})
    form = RoleModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(reverse('rbac:role_list'))
    return render(request, 'rbac/change.html', {'form': form,'cancel':origin_url})

def role_edit(request,pk):
    # 取到id的信息数据
    obj = models.Role.objects.filter(id=pk).first()
    origin_url = reverse('rbac:role_list')
    if not obj:
        return HttpResponse('角色不存在')
    if request.method == 'GET':
        form = RoleModelForm(instance=obj)
        return render(request, 'rbac/change.html', {'form': form})
    form = RoleModelForm(data=request.POST, instance=obj)
    if form.is_valid():
        form.save()
        return redirect(reverse('rbac:role_list'))
    return render(request, 'rbac/change.html', {'form': form,'cancel':origin_url})


def role_del(request,pk):
    obj2 = models.Role.objects.get(id=pk)
    if request.method == "GET":
        return render(request, 'rbac/role_del.html', {'obj2': obj2})
    obj2.delete()
    return redirect(reverse('rbac:role_list'))

rbac/templates/rbac/breadcrumb.html
{# 默认选中列表 #}
<div>
    <ol class="breadcrumb no-radius no-margin" style="border-bottom: 1px solid #ddd">
        {% for item in recode_list %}
            {% if item.class %}
                <li class="active">{{ item.title }}</li>
            {% else %}
            <li><a href="{{ item.url }}">{{ item.title }}</a></li>
            {% endif %}
        {% endfor %}
    </ol>
</div>

rbac/templates/rbac/change.html
{% extends 'layout.html' %}
{% block css %}
    <style>
        ul {
            list-style-type: none;
            padding: 0;
        }

        ul li {
            float: left;
            padding: 10px;
            padding-left: 0;
            width: 80px;
        }

        ul li i {
            font-size: 18px;
            margin-left: 5px;
            color: #6d6565;
        }

    </style>
{% endblock %}
{% block content %}
<div class="luffy-container">
    <form action="" class="form-horizontal" method="post" novalidate>
        {% csrf_token %}
        {% for field in form %}
                <div class="form-group">
                <label class="col-sm-2 control-label">{{ field.label }}</label>
                <div class="col-sm-8">
                    {{ field }} <span style="color: firebrick" class="pull-right">{{ field.errors.0 }}</span>
                </div>
                </div>
        {% endfor %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-8">
            <input type="submit" class="btn btn-primary" value="保存">

        </div>

    </div>

    </form>

</div>
{% endblock %}

rbac/templates/rbac/delete.html
{% extends 'layout.html' %}

{% block content %}
    <div class="luffy-container">
        <div class="alert alert-danger" role="alert">
            <form method="post">
                {% csrf_token %}
                <p style="font-size: 13px;"><i class="fa fa-warning" aria-hidden="true"></i> 删除后将不可恢复，请确定是否删除？</p>


                <div style="margin-top: 20px;">
                    <a href="{{ cancel }}" class="btn btn-default btn-sm">取消</a>

                    <input type="submit" class="btn btn-danger btn-sm" value="确 认">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

rbac/templates/rbac/distribute_permissions.html
{% extends 'layout.html' %}
{% load rbac %}
{% block css %}
    <style>
        table {
            font-size: 12px;
        }

        .user-area ul {
            padding-left: 20px;
        }

        .user-area li {
            cursor: pointer;
            padding: 2px 0;
        }

        .user-area li a {
            display: block;
        }

        .user-area li.active {
            font-weight: bold;
            color: red;
        }

        .user-area li.active a {
            color: red;
        }

        .role-area tr td a {
            display: block;
        }

        .role-area tr.active {
            background-color: #f1f7fd;
            border-left: 3px solid #fdc00f;
        }

        .panel-body {
            font-size: 12px;
        }

        .permission-area tr.root {
            background-color: #f1f7fd;
        }

        .permission-area tr.root td i {
            margin: 3px;
        }

        .permission-area .node {

        }

        .permission-area .node input[type='checkbox'] {
            margin: 0 5px;
        }

        .permission-area .node .parent {
            padding: 5px 0;
        }

        .permission-area .node label {
            font-weight: normal;
            margin-bottom: 0;
            font-size: 12px;
        }

        .permission-area .node .children {
            padding: 0 0 0 20px;
        }

        .permission-area .node .children .child {
            display: inline-block;
            margin: 2px 5px;
        }

        .select-help {
            float: right;
        }

        .select-help label {
            font-weight: normal;
            cursor: pointer;
        }

        .select-help .check-all {
            float: left;
            display: inline-block;
            margin-right: 8px;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="luffy-container">
        {# 一级菜单 #}
        <div class="col-md-3 user-area">
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <i class="fa fa-arrow-circle-right" aria-hidden="true"></i> 用户信息
                </div>
                <div class="panel-body">
                    <ul>
                        {% for user in all_user_list %}
                            <li class="{% if user.id|safe == user_id %}active{% endif %}">
                                <a href="?uid={{ user.id }}">{{ user.name }}</a>
                            </li>
                        {% endfor %}

                    </ul>
                </div>

            </div>
        </div>
        {# 二级菜单 #}
        <div class="col-md-3 role-area">
            <form action="" method="post">
                <input type="hidden" name="type" value="role">
                {% csrf_token %}
                <div class="panel panel-default">
                    <!-- Default panel contents -->
                    <div class="panel-heading">
                        <i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i> 角色
                        {% if user_id %}
                            <button href="#" class="right btn btn-success btn-xs"
                                    style="padding: 2px 8px;margin: -3px;">
                                <i class="fa fa-save" aria-hidden="true"></i>
                                保存
                            </button>
                        {% endif %}
                    </div>
                    <div class="panel-body">
                        提示:点击用户后才能为其分配角色
                    </div>
                    <!-- Table -->
                    <table class="table">
                        <thead>
                        <tr>
                            <th>角色</th>
                            <th>选择</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for row in all_role_list %}

                            <tr class="{% if row.id|safe == role_id %}active{% endif %} ">
                                <td>
                                    {% if user_id %}
                                        <a href="?uid={{ user_id }}&rid={{ row.id }}">{{ row.title }}</a>
                                    {% else %}
                                        <a href="?rid={{ row.id }}">{{ row.title }}</a>
                                    {% endif %}
                                </td>
                                <td><input type="checkbox" name="roles" value="{{ row.id }} "
                                           {% if row.id in user_has_roles_dict %}checked{% endif %}></td>

                            </tr>


                        {% endfor %}


                        </tbody>
                    </table>
                </div>
            </form>
        </div>
        {# 三级菜单 #}
        <div class="col-md-6 permission-area">
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="type" value="permission">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-apple" aria-hidden="true"></i> 权限分配
                        {% if role_id %}
                            <button href="#" class="right btn btn-success btn-xs"
                                    style="padding: 2px 8px;margin: -3px;">
                                <i class="fa fa-save" aria-hidden="true"></i>
                                保存
                            </button>
                        {% endif %}

                    </div>
                    <div class="panel-body" style="color: #d4d4d4;padding:10px  5px;">
                        提示：点击角色后才能为其分配权限
                    </div>
                    <table class="table">
                        <tbody>
                        {% for item in all_menu_list %}
                            <tr class="root">
                                <td>
                                    <i class="fa fa-caret-down" aria-hidden="true"></i>
                                    {{ item.title }}
                                    <div class="select-help">
                                        <div class="check-all">
                                            <label for="check-all_{{ item.id }}">全选</label>
                                            <input type="checkbox" id="check-all_{{ item.id }}">
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% if item.children %}
                                <tr class="node">
                                    <td>
                                        {% for node in item.children %}
                                            <div class="parent">

                                                <input type="checkbox" id="permission_{{ node.id }}"
                                                       {% if node.id in user_has_permissions_list %}checked{% endif %}
                                                       name="permissions" value="{{ node.id }}">

                                                {% if forloop.parentloop.last %}
                                                    <label for="permission_{{ node.id }}">{{ node.title }}</label>
                                                {% else %}
                                                    <label for="permission_{{ node.id }}">{{ node.title }}(菜单)</label>
                                                {% endif %}
                                            </div>
                                            <div class="children">
                                                {% for child in node.children %}
                                                    <div class="child">
                                                        <input type="checkbox" id="permission_{{ child.id }}"
                                                               name="permissions" value="{{ child.id }}"
                                                               {% if child.id in user_has_permissions_list %}checked{% endif %}>
                                                        <label for="permission_{{ child.id }}">{{ child.title }}</label>
                                                    </div>
                                                {% endfor %}

                                            </div>
                                        {% endfor %}
                                    </td>
                                </tr>

                            {% endif %}
                        {% endfor %}
                        </tbody>
                    </table>


                </div>
            </form>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script type="text/javascript">
        $(function () {
            $('.check-all input:checkbox').change(function () {
                $(this).parents('.root').next().find(':checkbox').prop('checked', $(this).prop('checked'))
            })
        })
    </script>
{% endblock %}

rbac/templates/rbac/multi_menu.html
{#动态生成二级菜单#}
<div class="multi-menu">
    {% for item in menu_dict.values %}
        <div class="item">
            <div class="title"><span class="icon-wrap"><i class="fa {{ item.icon }}"></i></span> {{ item.title }}</div>
            <div class="body {{ item.class }}">
                {% for per in item.children %}
                    <a class="{{ per.class }}" href="{{ per.url }}">{{ per.title }}</a>
                {% endfor %}
            </div>

        </div>
    {% endfor %}
</div>

rbac/templates/rbac/role_list.html
{% extends 'layout.html' %}
{% block content %}
    <div class="luffy-container">
        <div class="btn-group" style="margin:5px 0">
                {# 反向生成 #}
            <a href="{% url 'rbac:role_add' %}" class="btn btn-danger">
                <i class="fa fa-plus-square" aria-hidden="true"></i>
                添加角色
            </a>


        </div>
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>ID</th>
                <th>名称</th>
                <th>选项</th>

            </tr>
            </thead>
            <tbody>
            {% for data in roles %}
                <tr>
                    <td>{{ data.id }}</td>
                    <td>{{ data.title }}</td>

                    <td>


                        <a href="{% url 'rbac:role_edit' pk=data.id %}" class="btn btn-primary">编辑</a>


                        <a href="{% url 'rbac:role_del' pk=data.id%}" class="btn btn-danger">删除</a>

                    </td>

                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
{% endblock %}

rbac/templates/rbac/user_list.html
{% extends 'layout.html' %}
{% block content %}
    <div class="luffy-container">
        <div class="btn-group" style="margin:5px 0">
                {# 反向生成 #}
            <a href="{% url 'rbac:user_add' %}" class="btn btn-danger">
                <i class="fa fa-plus-square" aria-hidden="true"></i>
                添加用户
            </a>


        </div>
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>序号</th>
                <th>用户名</th>
                <th>邮箱</th>
                <th>重置密码</th>
                <th>选项</th>
            </tr>
            </thead>
            <tbody>
            {% for data in users %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ data.name }}</td>
                    <td>{{ data.email }}</td>
                    <td><a href="{% url 'rbac:user_reset_pwd' pk=data.id %}">重置密码</a></td>
                    <td>


                        <a href="{% url 'rbac:user_edit' pk=data.id %}" class="btn btn-primary">编辑</a>
                        <a href="{% url 'rbac:user_del' pk=data.id%}" class="btn btn-danger">删除</a>

                    </td>

                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
{% endblock %}